name: Build and upload to PyPI

on:
  workflow_dispatch:

jobs:

  build_dist:
    name: Build distributions
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python:
            - 3.8

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Build dist
        run: pipx run build --sdist --wheel

      - uses: actions/upload-artifact@v2
        with:
          path: |
            dist/*.tar.gz
            dist/*.whl  

  upload_pypi:
    needs: [build_dist]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}